# Generated by Django 3.2.15 on 2022-08-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220806_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=150, null=True, verbose_name='date of birth'),
        ),
    ]
